general {
    lock_cmd = pidof hyprlock || hyprlock       # Commande pour verrouiller
    before_sleep_cmd = loginctl lock-session    # Verrouiller AVANT la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # Rallumer l'écran au réveil
}

listener {
    timeout = 300                                # 5 minutes
    on-timeout = loginctl lock-session           # Verrouille l'écran
}

listener {
    timeout = 330                                # 5.5 minutes
    on-timeout = hyprctl dispatch dpms off       # Éteint l'écran pour économiser la batterie
    on-resume = hyprctl dispatch dpms on         # Rallume l'écran quand on bouge la souris
}
