-- Generated by nwg-displays on 2026-09-18 at 11:03:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "0x280",
    scale = 1.0999999999999996,
    vrr = 0
})
