-- Generated by nwg-displays on 2026-09-11 at 21:31:40. Do not edit manually.

hl.monitor({
  output = "eDP-1",
  mode = "1920x1200@60.0",
  position = "0x0",
  scale = 1.5,
  vrr = 0
})
hl.monitor({
  output = "HDMI-A-1",
  mode = "2560x1440@144.0",
  position = "1280x0",
  scale = 1.0,
  vrr = 0
})
